/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export class ApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:44300";
    }

    get(contentItemId: string | null): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/content/{contentItemId}";
        if (contentItemId === undefined || contentItemId === null)
            throw new Error("The parameter 'contentItemId' must be defined.");
        url_ = url_.replace("{contentItemId}", encodeURIComponent("" + contentItemId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(<any>null);
    }

    delete(contentItemId: string | null): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/content/{contentItemId}";
        if (contentItemId === undefined || contentItemId === null)
            throw new Error("The parameter 'contentItemId' must be defined.");
        url_ = url_.replace("{contentItemId}", encodeURIComponent("" + contentItemId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "DELETE",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(<any>null);
    }

    post(draft: boolean | undefined, model: ContentItem): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/content?";
        if (draft === null)
            throw new Error("The parameter 'draft' cannot be null.");
        else if (draft !== undefined)
            url_ += "draft=" + encodeURIComponent("" + draft) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPost(_response);
        });
    }

    protected processPost(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(<any>null);
    }
}

export class FooClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:44300";
    }

    post(createDto: CreateFooDto): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/foo";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createDto);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPost(_response);
        });
    }

    protected processPost(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(<any>null);
    }

    put(updateDto: UpdateFooDto): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/foo";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(updateDto);

        let options_ = <RequestInit>{
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPut(_response);
        });
    }

    protected processPut(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(<any>null);
    }
}

export class ContentElement implements IContentElement {

    constructor(data?: IContentElement) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): ContentElement {
        data = typeof data === 'object' ? data : {};
        let result = new ContentElement();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IContentElement {
}

export class ContentItem extends ContentElement implements IContentItem {
    id?: number;
    contentItemId?: string | undefined;
    contentItemVersionId?: string | undefined;
    contentType?: string | undefined;
    published?: boolean;
    latest?: boolean;
    modifiedUtc?: Date | undefined;
    publishedUtc?: Date | undefined;
    createdUtc?: Date | undefined;
    owner?: string | undefined;
    author?: string | undefined;
    displayText?: string | undefined;

    constructor(data?: IContentItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.id = _data["id"];
            this.contentItemId = _data["contentItemId"];
            this.contentItemVersionId = _data["contentItemVersionId"];
            this.contentType = _data["contentType"];
            this.published = _data["published"];
            this.latest = _data["latest"];
            this.modifiedUtc = _data["modifiedUtc"] ? new Date(_data["modifiedUtc"].toString()) : <any>undefined;
            this.publishedUtc = _data["publishedUtc"] ? new Date(_data["publishedUtc"].toString()) : <any>undefined;
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : <any>undefined;
            this.owner = _data["owner"];
            this.author = _data["author"];
            this.displayText = _data["displayText"];
        }
    }

    static fromJS(data: any): ContentItem {
        data = typeof data === 'object' ? data : {};
        let result = new ContentItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["contentItemId"] = this.contentItemId;
        data["contentItemVersionId"] = this.contentItemVersionId;
        data["contentType"] = this.contentType;
        data["published"] = this.published;
        data["latest"] = this.latest;
        data["modifiedUtc"] = this.modifiedUtc ? this.modifiedUtc.toISOString() : <any>undefined;
        data["publishedUtc"] = this.publishedUtc ? this.publishedUtc.toISOString() : <any>undefined;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : <any>undefined;
        data["owner"] = this.owner;
        data["author"] = this.author;
        data["displayText"] = this.displayText;
        super.toJSON(data);
        return data; 
    }
}

export interface IContentItem extends IContentElement {
    id?: number;
    contentItemId?: string | undefined;
    contentItemVersionId?: string | undefined;
    contentType?: string | undefined;
    published?: boolean;
    latest?: boolean;
    modifiedUtc?: Date | undefined;
    publishedUtc?: Date | undefined;
    createdUtc?: Date | undefined;
    owner?: string | undefined;
    author?: string | undefined;
    displayText?: string | undefined;
}

export class CreateFooDto implements ICreateFooDto {
    text?: string | undefined;

    protected _discriminator: string;

    constructor(data?: ICreateFooDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        this._discriminator = "CreateFooDto";
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
        }
    }

    static fromJS(data: any): CreateFooDto {
        data = typeof data === 'object' ? data : {};
        if (data["discriminator"] === "UpdateFooDto") {
            let result = new UpdateFooDto();
            result.init(data);
            return result;
        }
        let result = new CreateFooDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["discriminator"] = this._discriminator; 
        data["text"] = this.text;
        return data; 
    }
}

export interface ICreateFooDto {
    text?: string | undefined;
}

export class UpdateFooDto extends CreateFooDto implements IUpdateFooDto {

    constructor(data?: IUpdateFooDto) {
        super(data);
        this._discriminator = "UpdateFooDto";
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): UpdateFooDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateFooDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IUpdateFooDto extends ICreateFooDto {
}

export abstract class ContentElementDto implements IContentElementDto {

    constructor(data?: IContentElementDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): ContentElementDto {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'ContentElementDto' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IContentElementDto {
}

export class ContentFieldDto extends ContentElementDto implements IContentFieldDto {

    constructor(data?: IContentFieldDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ContentFieldDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContentFieldDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IContentFieldDto extends IContentElementDto {
}

export class TextFieldDto extends ContentFieldDto implements ITextFieldDto {
    text?: string | undefined;

    constructor(data?: ITextFieldDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.text = _data["text"];
        }
    }

    static fromJS(data: any): TextFieldDto {
        data = typeof data === 'object' ? data : {};
        let result = new TextFieldDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        super.toJSON(data);
        return data; 
    }
}

export interface ITextFieldDto extends IContentFieldDto {
    text?: string | undefined;
}

export class ContentField extends ContentElement implements IContentField {

    constructor(data?: IContentField) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ContentField {
        data = typeof data === 'object' ? data : {};
        let result = new ContentField();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IContentField extends IContentElement {
}

export class HtmlFieldDto extends ContentFieldDto implements IHtmlFieldDto {
    html?: string | undefined;

    constructor(data?: IHtmlFieldDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.html = _data["html"];
        }
    }

    static fromJS(data: any): HtmlFieldDto {
        data = typeof data === 'object' ? data : {};
        let result = new HtmlFieldDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["html"] = this.html;
        super.toJSON(data);
        return data; 
    }
}

export interface IHtmlFieldDto extends IContentFieldDto {
    html?: string | undefined;
}

export class ContentPickerFieldDto extends ContentFieldDto implements IContentPickerFieldDto {
    contentItemIds?: string[] | undefined;

    constructor(data?: IContentPickerFieldDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["contentItemIds"])) {
                this.contentItemIds = [] as any;
                for (let item of _data["contentItemIds"])
                    this.contentItemIds!.push(item);
            }
        }
    }

    static fromJS(data: any): ContentPickerFieldDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContentPickerFieldDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.contentItemIds)) {
            data["contentItemIds"] = [];
            for (let item of this.contentItemIds)
                data["contentItemIds"].push(item);
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IContentPickerFieldDto extends IContentFieldDto {
    contentItemIds?: string[] | undefined;
}

export class MediaFieldDto extends ContentFieldDto implements IMediaFieldDto {
    paths?: string[] | undefined;

    constructor(data?: IMediaFieldDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["paths"])) {
                this.paths = [] as any;
                for (let item of _data["paths"])
                    this.paths!.push(item);
            }
        }
    }

    static fromJS(data: any): MediaFieldDto {
        data = typeof data === 'object' ? data : {};
        let result = new MediaFieldDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.paths)) {
            data["paths"] = [];
            for (let item of this.paths)
                data["paths"].push(item);
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IMediaFieldDto extends IContentFieldDto {
    paths?: string[] | undefined;
}

export class TaxonomyFieldDto extends ContentFieldDto implements ITaxonomyFieldDto {
    taxonomyContentItemId?: string | undefined;
    termContentItemIds?: string[] | undefined;

    constructor(data?: ITaxonomyFieldDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.taxonomyContentItemId = _data["taxonomyContentItemId"];
            if (Array.isArray(_data["termContentItemIds"])) {
                this.termContentItemIds = [] as any;
                for (let item of _data["termContentItemIds"])
                    this.termContentItemIds!.push(item);
            }
        }
    }

    static fromJS(data: any): TaxonomyFieldDto {
        data = typeof data === 'object' ? data : {};
        let result = new TaxonomyFieldDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["taxonomyContentItemId"] = this.taxonomyContentItemId;
        if (Array.isArray(this.termContentItemIds)) {
            data["termContentItemIds"] = [];
            for (let item of this.termContentItemIds)
                data["termContentItemIds"].push(item);
        }
        super.toJSON(data);
        return data; 
    }
}

export interface ITaxonomyFieldDto extends IContentFieldDto {
    taxonomyContentItemId?: string | undefined;
    termContentItemIds?: string[] | undefined;
}

export class ContentItemDto extends ContentElementDto implements IContentItemDto {
    id?: number;
    contentItemId?: string | undefined;
    contentItemVersionId?: string | undefined;
    published?: boolean;
    latest?: boolean;
    modifiedUtc?: Date | undefined;
    publishedUtc?: Date | undefined;
    createdUtc?: Date | undefined;
    owner?: string | undefined;
    author?: string | undefined;
    displayText?: string | undefined;

    protected _discriminator: string;

    constructor(data?: IContentItemDto) {
        super(data);
        this._discriminator = "ContentItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.id = _data["id"];
            this.contentItemId = _data["contentItemId"];
            this.contentItemVersionId = _data["contentItemVersionId"];
            this.published = _data["published"];
            this.latest = _data["latest"];
            this.modifiedUtc = _data["modifiedUtc"] ? new Date(_data["modifiedUtc"].toString()) : <any>undefined;
            this.publishedUtc = _data["publishedUtc"] ? new Date(_data["publishedUtc"].toString()) : <any>undefined;
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : <any>undefined;
            this.owner = _data["owner"];
            this.author = _data["author"];
            this.displayText = _data["displayText"];
        }
    }

    static fromJS(data: any): ContentItemDto {
        data = typeof data === 'object' ? data : {};
        if (data["contentType"] === "MenuItemDto") {
            let result = new MenuItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "LinkMenuItemItemDto") {
            let result = new LinkMenuItemItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "ContentMenuItemItemDto") {
            let result = new ContentMenuItemItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "TaxonomyItemDto") {
            let result = new TaxonomyItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "ArticleItemDto") {
            let result = new ArticleItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "LiquidPageItemDto") {
            let result = new LiquidPageItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "BlogPostItemDto") {
            let result = new BlogPostItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "BlogItemDto") {
            let result = new BlogItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "ContainerItemDto") {
            let result = new ContainerItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "BlockquoteItemDto") {
            let result = new BlockquoteItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "ImageWidgetItemDto") {
            let result = new ImageWidgetItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "LiquidWidgetItemDto") {
            let result = new LiquidWidgetItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "ImageItemDto") {
            let result = new ImageItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "ParagraphItemDto") {
            let result = new ParagraphItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "RawHtmlItemDto") {
            let result = new RawHtmlItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "PageItemDto") {
            let result = new PageItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "TagItemDto") {
            let result = new TagItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "CategoryItemDto") {
            let result = new CategoryItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "BarItemDto") {
            let result = new BarItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "FooItemDto") {
            let result = new FooItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "BagItemDto") {
            let result = new BagItemDto();
            result.init(data);
            return result;
        }
        if (data["contentType"] === "FooTextItemDto") {
            let result = new FooTextItemDto();
            result.init(data);
            return result;
        }
        let result = new ContentItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["contentType"] = this._discriminator; 
        data["id"] = this.id;
        data["contentItemId"] = this.contentItemId;
        data["contentItemVersionId"] = this.contentItemVersionId;
        data["published"] = this.published;
        data["latest"] = this.latest;
        data["modifiedUtc"] = this.modifiedUtc ? this.modifiedUtc.toISOString() : <any>undefined;
        data["publishedUtc"] = this.publishedUtc ? this.publishedUtc.toISOString() : <any>undefined;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : <any>undefined;
        data["owner"] = this.owner;
        data["author"] = this.author;
        data["displayText"] = this.displayText;
        super.toJSON(data);
        return data; 
    }
}

export interface IContentItemDto extends IContentElementDto {
    id?: number;
    contentItemId?: string | undefined;
    contentItemVersionId?: string | undefined;
    published?: boolean;
    latest?: boolean;
    modifiedUtc?: Date | undefined;
    publishedUtc?: Date | undefined;
    createdUtc?: Date | undefined;
    owner?: string | undefined;
    author?: string | undefined;
    displayText?: string | undefined;
}

export class ContentPartDto extends ContentElementDto implements IContentPartDto {

    constructor(data?: IContentPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ContentPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContentPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IContentPartDto extends IContentElementDto {
}

export class CommonPartDto extends ContentPartDto implements ICommonPartDto {

    constructor(data?: ICommonPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): CommonPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new CommonPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface ICommonPartDto extends IContentPartDto {
}

export class ContentPart extends ContentElement implements IContentPart {

    constructor(data?: IContentPart) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ContentPart {
        data = typeof data === 'object' ? data : {};
        let result = new ContentPart();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IContentPart extends IContentElement {
}

export class WidgetMetadataDto extends ContentPartDto implements IWidgetMetadataDto {
    renderTitle?: boolean;
    position?: string | undefined;

    constructor(data?: IWidgetMetadataDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.renderTitle = _data["renderTitle"];
            this.position = _data["position"];
        }
    }

    static fromJS(data: any): WidgetMetadataDto {
        data = typeof data === 'object' ? data : {};
        let result = new WidgetMetadataDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["renderTitle"] = this.renderTitle;
        data["position"] = this.position;
        super.toJSON(data);
        return data; 
    }
}

export interface IWidgetMetadataDto extends IContentPartDto {
    renderTitle?: boolean;
    position?: string | undefined;
}

export class FlowMetadataDto extends ContentPartDto implements IFlowMetadataDto {
    alignment?: FlowAlignment;
    size?: number;

    constructor(data?: IFlowMetadataDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.alignment = _data["alignment"];
            this.size = _data["size"];
        }
    }

    static fromJS(data: any): FlowMetadataDto {
        data = typeof data === 'object' ? data : {};
        let result = new FlowMetadataDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["alignment"] = this.alignment;
        data["size"] = this.size;
        super.toJSON(data);
        return data; 
    }
}

export interface IFlowMetadataDto extends IContentPartDto {
    alignment?: FlowAlignment;
    size?: number;
}

export enum FlowAlignment {
    Left = 0,
    Center = 1,
    Right = 2,
    Justify = 3,
}

export class LayerMetadataDto extends ContentPartDto implements ILayerMetadataDto {
    renderTitle?: boolean;
    position?: number;
    zone?: string | undefined;
    layer?: string | undefined;

    constructor(data?: ILayerMetadataDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.renderTitle = _data["renderTitle"];
            this.position = _data["position"];
            this.zone = _data["zone"];
            this.layer = _data["layer"];
        }
    }

    static fromJS(data: any): LayerMetadataDto {
        data = typeof data === 'object' ? data : {};
        let result = new LayerMetadataDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["renderTitle"] = this.renderTitle;
        data["position"] = this.position;
        data["zone"] = this.zone;
        data["layer"] = this.layer;
        super.toJSON(data);
        return data; 
    }
}

export interface ILayerMetadataDto extends IContentPartDto {
    renderTitle?: boolean;
    position?: number;
    zone?: string | undefined;
    layer?: string | undefined;
}

export class ContainedPartDto extends ContentPartDto implements IContainedPartDto {
    listContentItemId?: string | undefined;
    order?: number;

    constructor(data?: IContainedPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.listContentItemId = _data["listContentItemId"];
            this.order = _data["order"];
        }
    }

    static fromJS(data: any): ContainedPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContainedPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["listContentItemId"] = this.listContentItemId;
        data["order"] = this.order;
        super.toJSON(data);
        return data; 
    }
}

export interface IContainedPartDto extends IContentPartDto {
    listContentItemId?: string | undefined;
    order?: number;
}

export class MenuItemsListPartDto extends ContentPartDto implements IMenuItemsListPartDto {
    menuItems?: ContentItem[] | undefined;

    constructor(data?: IMenuItemsListPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["menuItems"])) {
                this.menuItems = [] as any;
                for (let item of _data["menuItems"])
                    this.menuItems!.push(ContentItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): MenuItemsListPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new MenuItemsListPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.menuItems)) {
            data["menuItems"] = [];
            for (let item of this.menuItems)
                data["menuItems"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IMenuItemsListPartDto extends IContentPartDto {
    menuItems?: ContentItem[] | undefined;
}

export class TaxonomyPartDto extends ContentPartDto implements ITaxonomyPartDto {
    termContentType?: string | undefined;
    terms?: ContentItem[] | undefined;

    constructor(data?: ITaxonomyPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.termContentType = _data["termContentType"];
            if (Array.isArray(_data["terms"])) {
                this.terms = [] as any;
                for (let item of _data["terms"])
                    this.terms!.push(ContentItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TaxonomyPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new TaxonomyPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["termContentType"] = this.termContentType;
        if (Array.isArray(this.terms)) {
            data["terms"] = [];
            for (let item of this.terms)
                data["terms"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface ITaxonomyPartDto extends IContentPartDto {
    termContentType?: string | undefined;
    terms?: ContentItem[] | undefined;
}

export class TermPartDto extends ContentPartDto implements ITermPartDto {
    taxonomyContentItemId?: string | undefined;

    constructor(data?: ITermPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.taxonomyContentItemId = _data["taxonomyContentItemId"];
        }
    }

    static fromJS(data: any): TermPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new TermPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["taxonomyContentItemId"] = this.taxonomyContentItemId;
        super.toJSON(data);
        return data; 
    }
}

export interface ITermPartDto extends IContentPartDto {
    taxonomyContentItemId?: string | undefined;
}

export class SamplePartDto extends ContentPartDto implements ISamplePartDto {
    show?: boolean;

    constructor(data?: ISamplePartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.show = _data["show"];
        }
    }

    static fromJS(data: any): SamplePartDto {
        data = typeof data === 'object' ? data : {};
        let result = new SamplePartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["show"] = this.show;
        super.toJSON(data);
        return data; 
    }
}

export interface ISamplePartDto extends IContentPartDto {
    show?: boolean;
}

export class LiquidPartDto extends ContentPartDto implements ILiquidPartDto {
    liquid?: string | undefined;

    constructor(data?: ILiquidPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.liquid = _data["liquid"];
        }
    }

    static fromJS(data: any): LiquidPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new LiquidPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["liquid"] = this.liquid;
        super.toJSON(data);
        return data; 
    }
}

export interface ILiquidPartDto extends IContentPartDto {
    liquid?: string | undefined;
}

export class AliasPartDto extends ContentPartDto implements IAliasPartDto {
    alias?: string | undefined;

    constructor(data?: IAliasPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.alias = _data["alias"];
        }
    }

    static fromJS(data: any): AliasPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new AliasPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["alias"] = this.alias;
        super.toJSON(data);
        return data; 
    }
}

export interface IAliasPartDto extends IContentPartDto {
    alias?: string | undefined;
}

export class AutoroutePartDto extends ContentPartDto implements IAutoroutePartDto {
    path?: string | undefined;
    setHomepage?: boolean;
    disabled?: boolean;
    routeContainedItems?: boolean;
    absolute?: boolean;

    constructor(data?: IAutoroutePartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.path = _data["path"];
            this.setHomepage = _data["setHomepage"];
            this.disabled = _data["disabled"];
            this.routeContainedItems = _data["routeContainedItems"];
            this.absolute = _data["absolute"];
        }
    }

    static fromJS(data: any): AutoroutePartDto {
        data = typeof data === 'object' ? data : {};
        let result = new AutoroutePartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["path"] = this.path;
        data["setHomepage"] = this.setHomepage;
        data["disabled"] = this.disabled;
        data["routeContainedItems"] = this.routeContainedItems;
        data["absolute"] = this.absolute;
        super.toJSON(data);
        return data; 
    }
}

export interface IAutoroutePartDto extends IContentPartDto {
    path?: string | undefined;
    setHomepage?: boolean;
    disabled?: boolean;
    routeContainedItems?: boolean;
    absolute?: boolean;
}

export class PreviewPartDto extends ContentPartDto implements IPreviewPartDto {

    constructor(data?: IPreviewPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): PreviewPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new PreviewPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IPreviewPartDto extends IContentPartDto {
}

export class WidgetsListPartDto extends ContentPartDto implements IWidgetsListPartDto {
    widgets?: { [key: string]: ContentItemDto[]; } | undefined;

    constructor(data?: IWidgetsListPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (_data["widgets"]) {
                this.widgets = {} as any;
                for (let key in _data["widgets"]) {
                    if (_data["widgets"].hasOwnProperty(key))
                        this.widgets![key] = _data["widgets"][key] ? _data["widgets"][key].map((i: any) => ContentItemDto.fromJS(i)) : [];
                }
            }
        }
    }

    static fromJS(data: any): WidgetsListPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new WidgetsListPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.widgets) {
            data["widgets"] = {};
            for (let key in this.widgets) {
                if (this.widgets.hasOwnProperty(key))
                    data["widgets"][key] = this.widgets[key];
            }
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IWidgetsListPartDto extends IContentPartDto {
    widgets?: { [key: string]: ContentItemDto[]; } | undefined;
}

export class FlowPartDto extends ContentPartDto implements IFlowPartDto {
    widgets?: ContentItemDto[] | undefined;

    constructor(data?: IFlowPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["widgets"])) {
                this.widgets = [] as any;
                for (let item of _data["widgets"])
                    this.widgets!.push(ContentItemDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): FlowPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new FlowPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.widgets)) {
            data["widgets"] = [];
            for (let item of this.widgets)
                data["widgets"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IFlowPartDto extends IContentPartDto {
    widgets?: ContentItemDto[] | undefined;
}

export class BagPartDto extends ContentPartDto implements IBagPartDto {
    contentItems?: ContentItemDto[] | undefined;

    constructor(data?: IBagPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["contentItems"])) {
                this.contentItems = [] as any;
                for (let item of _data["contentItems"])
                    this.contentItems!.push(ContentItemDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BagPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new BagPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.contentItems)) {
            data["contentItems"] = [];
            for (let item of this.contentItems)
                data["contentItems"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IBagPartDto extends IContentPartDto {
    contentItems?: ContentItemDto[] | undefined;
}

export class HtmlBodyPartDto extends ContentPartDto implements IHtmlBodyPartDto {
    fooField?: TextFieldDto | undefined;
    html?: string | undefined;

    constructor(data?: IHtmlBodyPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.fooField = _data["fooField"] ? TextFieldDto.fromJS(_data["fooField"]) : <any>undefined;
            this.html = _data["html"];
        }
    }

    static fromJS(data: any): HtmlBodyPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new HtmlBodyPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fooField"] = this.fooField ? this.fooField.toJSON() : <any>undefined;
        data["html"] = this.html;
        super.toJSON(data);
        return data; 
    }
}

export interface IHtmlBodyPartDto extends IContentPartDto {
    fooField?: TextFieldDto | undefined;
    html?: string | undefined;
}

export class ListPartDto extends ContentPartDto implements IListPartDto {

    constructor(data?: IListPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ListPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new ListPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IListPartDto extends IContentPartDto {
}

export class MarkdownBodyPartDto extends ContentPartDto implements IMarkdownBodyPartDto {
    markdown?: string | undefined;

    constructor(data?: IMarkdownBodyPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.markdown = _data["markdown"];
        }
    }

    static fromJS(data: any): MarkdownBodyPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new MarkdownBodyPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["markdown"] = this.markdown;
        super.toJSON(data);
        return data; 
    }
}

export interface IMarkdownBodyPartDto extends IContentPartDto {
    markdown?: string | undefined;
}

export class TitlePartDto extends ContentPartDto implements ITitlePartDto {
    title?: string | undefined;

    constructor(data?: ITitlePartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.title = _data["title"];
        }
    }

    static fromJS(data: any): TitlePartDto {
        data = typeof data === 'object' ? data : {};
        let result = new TitlePartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        super.toJSON(data);
        return data; 
    }
}

export interface ITitlePartDto extends IContentPartDto {
    title?: string | undefined;
}

export class MenuPartDto extends ContentPartDto implements IMenuPartDto {

    constructor(data?: IMenuPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): MenuPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new MenuPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IMenuPartDto extends IContentPartDto {
}

export class MenuItemPartDto extends ContentPartDto implements IMenuItemPartDto {

    constructor(data?: IMenuItemPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): MenuItemPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new MenuItemPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IMenuItemPartDto extends IContentPartDto {
}

export class LinkMenuItemPartDto extends ContentPartDto implements ILinkMenuItemPartDto {
    name?: string | undefined;
    url?: string | undefined;

    constructor(data?: ILinkMenuItemPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.name = _data["name"];
            this.url = _data["url"];
        }
    }

    static fromJS(data: any): LinkMenuItemPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new LinkMenuItemPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["url"] = this.url;
        super.toJSON(data);
        return data; 
    }
}

export interface ILinkMenuItemPartDto extends IContentPartDto {
    name?: string | undefined;
    url?: string | undefined;
}

export class ContentMenuItemPartDto extends ContentPartDto implements IContentMenuItemPartDto {
    selectedContentItem?: ContentPickerFieldDto | undefined;
    name?: string | undefined;

    constructor(data?: IContentMenuItemPartDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.selectedContentItem = _data["selectedContentItem"] ? ContentPickerFieldDto.fromJS(_data["selectedContentItem"]) : <any>undefined;
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): ContentMenuItemPartDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContentMenuItemPartDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["selectedContentItem"] = this.selectedContentItem ? this.selectedContentItem.toJSON() : <any>undefined;
        data["name"] = this.name;
        super.toJSON(data);
        return data; 
    }
}

export interface IContentMenuItemPartDto extends IContentPartDto {
    selectedContentItem?: ContentPickerFieldDto | undefined;
    name?: string | undefined;
}

export class MenuItemDto extends ContentItemDto implements IMenuItemDto {
    titlePart?: TitlePartDto | undefined;
    aliasPart?: AliasPartDto | undefined;
    menuPart?: MenuPartDto | undefined;
    menuItemsListPart?: MenuItemsListPartDto | undefined;

    constructor(data?: IMenuItemDto) {
        super(data);
        this._discriminator = "MenuItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
            this.aliasPart = _data["aliasPart"] ? AliasPartDto.fromJS(_data["aliasPart"]) : <any>undefined;
            this.menuPart = _data["menuPart"] ? MenuPartDto.fromJS(_data["menuPart"]) : <any>undefined;
            this.menuItemsListPart = _data["menuItemsListPart"] ? MenuItemsListPartDto.fromJS(_data["menuItemsListPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): MenuItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new MenuItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        data["aliasPart"] = this.aliasPart ? this.aliasPart.toJSON() : <any>undefined;
        data["menuPart"] = this.menuPart ? this.menuPart.toJSON() : <any>undefined;
        data["menuItemsListPart"] = this.menuItemsListPart ? this.menuItemsListPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IMenuItemDto extends IContentItemDto {
    titlePart?: TitlePartDto | undefined;
    aliasPart?: AliasPartDto | undefined;
    menuPart?: MenuPartDto | undefined;
    menuItemsListPart?: MenuItemsListPartDto | undefined;
}

export class LinkMenuItemDto extends ContentPartDto implements ILinkMenuItemDto {

    constructor(data?: ILinkMenuItemDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): LinkMenuItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new LinkMenuItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface ILinkMenuItemDto extends IContentPartDto {
}

export class LinkMenuItemItemDto extends ContentItemDto implements ILinkMenuItemItemDto {
    linkMenuItem?: LinkMenuItemDto | undefined;
    linkMenuItemPart?: LinkMenuItemPartDto | undefined;

    constructor(data?: ILinkMenuItemItemDto) {
        super(data);
        this._discriminator = "LinkMenuItemItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.linkMenuItem = _data["linkMenuItem"] ? LinkMenuItemDto.fromJS(_data["linkMenuItem"]) : <any>undefined;
            this.linkMenuItemPart = _data["linkMenuItemPart"] ? LinkMenuItemPartDto.fromJS(_data["linkMenuItemPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): LinkMenuItemItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new LinkMenuItemItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["linkMenuItem"] = this.linkMenuItem ? this.linkMenuItem.toJSON() : <any>undefined;
        data["linkMenuItemPart"] = this.linkMenuItemPart ? this.linkMenuItemPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface ILinkMenuItemItemDto extends IContentItemDto {
    linkMenuItem?: LinkMenuItemDto | undefined;
    linkMenuItemPart?: LinkMenuItemPartDto | undefined;
}

export class ContentMenuItemDto extends ContentPartDto implements IContentMenuItemDto {

    constructor(data?: IContentMenuItemDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ContentMenuItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContentMenuItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IContentMenuItemDto extends IContentPartDto {
}

export class ContentMenuItemItemDto extends ContentItemDto implements IContentMenuItemItemDto {
    contentMenuItem?: ContentMenuItemDto | undefined;
    contentMenuItemPart?: ContentMenuItemPartDto | undefined;

    constructor(data?: IContentMenuItemItemDto) {
        super(data);
        this._discriminator = "ContentMenuItemItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.contentMenuItem = _data["contentMenuItem"] ? ContentMenuItemDto.fromJS(_data["contentMenuItem"]) : <any>undefined;
            this.contentMenuItemPart = _data["contentMenuItemPart"] ? ContentMenuItemPartDto.fromJS(_data["contentMenuItemPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ContentMenuItemItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContentMenuItemItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["contentMenuItem"] = this.contentMenuItem ? this.contentMenuItem.toJSON() : <any>undefined;
        data["contentMenuItemPart"] = this.contentMenuItemPart ? this.contentMenuItemPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IContentMenuItemItemDto extends IContentItemDto {
    contentMenuItem?: ContentMenuItemDto | undefined;
    contentMenuItemPart?: ContentMenuItemPartDto | undefined;
}

export class TaxonomyItemDto extends ContentItemDto implements ITaxonomyItemDto {
    titlePart?: TitlePartDto | undefined;
    aliasPart?: AliasPartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    taxonomyPart?: TaxonomyPartDto | undefined;

    constructor(data?: ITaxonomyItemDto) {
        super(data);
        this._discriminator = "TaxonomyItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
            this.aliasPart = _data["aliasPart"] ? AliasPartDto.fromJS(_data["aliasPart"]) : <any>undefined;
            this.autoroutePart = _data["autoroutePart"] ? AutoroutePartDto.fromJS(_data["autoroutePart"]) : <any>undefined;
            this.taxonomyPart = _data["taxonomyPart"] ? TaxonomyPartDto.fromJS(_data["taxonomyPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): TaxonomyItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new TaxonomyItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        data["aliasPart"] = this.aliasPart ? this.aliasPart.toJSON() : <any>undefined;
        data["autoroutePart"] = this.autoroutePart ? this.autoroutePart.toJSON() : <any>undefined;
        data["taxonomyPart"] = this.taxonomyPart ? this.taxonomyPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface ITaxonomyItemDto extends IContentItemDto {
    titlePart?: TitlePartDto | undefined;
    aliasPart?: AliasPartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    taxonomyPart?: TaxonomyPartDto | undefined;
}

export class ArticleDto extends ContentPartDto implements IArticleDto {
    subtitle?: TextFieldDto | undefined;
    image?: MediaFieldDto | undefined;

    constructor(data?: IArticleDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.subtitle = _data["subtitle"] ? TextFieldDto.fromJS(_data["subtitle"]) : <any>undefined;
            this.image = _data["image"] ? MediaFieldDto.fromJS(_data["image"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ArticleDto {
        data = typeof data === 'object' ? data : {};
        let result = new ArticleDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["subtitle"] = this.subtitle ? this.subtitle.toJSON() : <any>undefined;
        data["image"] = this.image ? this.image.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IArticleDto extends IContentPartDto {
    subtitle?: TextFieldDto | undefined;
    image?: MediaFieldDto | undefined;
}

export class ArticleItemDto extends ContentItemDto implements IArticleItemDto {
    article?: ArticleDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    htmlBodyPart?: HtmlBodyPartDto | undefined;
    titlePart?: TitlePartDto | undefined;

    constructor(data?: IArticleItemDto) {
        super(data);
        this._discriminator = "ArticleItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.article = _data["article"] ? ArticleDto.fromJS(_data["article"]) : <any>undefined;
            this.autoroutePart = _data["autoroutePart"] ? AutoroutePartDto.fromJS(_data["autoroutePart"]) : <any>undefined;
            this.htmlBodyPart = _data["htmlBodyPart"] ? HtmlBodyPartDto.fromJS(_data["htmlBodyPart"]) : <any>undefined;
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ArticleItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new ArticleItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["article"] = this.article ? this.article.toJSON() : <any>undefined;
        data["autoroutePart"] = this.autoroutePart ? this.autoroutePart.toJSON() : <any>undefined;
        data["htmlBodyPart"] = this.htmlBodyPart ? this.htmlBodyPart.toJSON() : <any>undefined;
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IArticleItemDto extends IContentItemDto {
    article?: ArticleDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    htmlBodyPart?: HtmlBodyPartDto | undefined;
    titlePart?: TitlePartDto | undefined;
}

export class LiquidPageDto extends ContentPartDto implements ILiquidPageDto {

    constructor(data?: ILiquidPageDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): LiquidPageDto {
        data = typeof data === 'object' ? data : {};
        let result = new LiquidPageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface ILiquidPageDto extends IContentPartDto {
}

export class LiquidPageItemDto extends ContentItemDto implements ILiquidPageItemDto {
    liquidPage?: LiquidPageDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    liquidPart?: LiquidPartDto | undefined;
    titlePart?: TitlePartDto | undefined;

    constructor(data?: ILiquidPageItemDto) {
        super(data);
        this._discriminator = "LiquidPageItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.liquidPage = _data["liquidPage"] ? LiquidPageDto.fromJS(_data["liquidPage"]) : <any>undefined;
            this.autoroutePart = _data["autoroutePart"] ? AutoroutePartDto.fromJS(_data["autoroutePart"]) : <any>undefined;
            this.liquidPart = _data["liquidPart"] ? LiquidPartDto.fromJS(_data["liquidPart"]) : <any>undefined;
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): LiquidPageItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new LiquidPageItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["liquidPage"] = this.liquidPage ? this.liquidPage.toJSON() : <any>undefined;
        data["autoroutePart"] = this.autoroutePart ? this.autoroutePart.toJSON() : <any>undefined;
        data["liquidPart"] = this.liquidPart ? this.liquidPart.toJSON() : <any>undefined;
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface ILiquidPageItemDto extends IContentItemDto {
    liquidPage?: LiquidPageDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    liquidPart?: LiquidPartDto | undefined;
    titlePart?: TitlePartDto | undefined;
}

export class BlogPostDto extends ContentPartDto implements IBlogPostDto {
    subtitle?: TextFieldDto | undefined;
    image?: MediaFieldDto | undefined;
    tags?: TaxonomyFieldDto | undefined;
    category?: TaxonomyFieldDto | undefined;

    constructor(data?: IBlogPostDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.subtitle = _data["subtitle"] ? TextFieldDto.fromJS(_data["subtitle"]) : <any>undefined;
            this.image = _data["image"] ? MediaFieldDto.fromJS(_data["image"]) : <any>undefined;
            this.tags = _data["tags"] ? TaxonomyFieldDto.fromJS(_data["tags"]) : <any>undefined;
            this.category = _data["category"] ? TaxonomyFieldDto.fromJS(_data["category"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BlogPostDto {
        data = typeof data === 'object' ? data : {};
        let result = new BlogPostDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["subtitle"] = this.subtitle ? this.subtitle.toJSON() : <any>undefined;
        data["image"] = this.image ? this.image.toJSON() : <any>undefined;
        data["tags"] = this.tags ? this.tags.toJSON() : <any>undefined;
        data["category"] = this.category ? this.category.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IBlogPostDto extends IContentPartDto {
    subtitle?: TextFieldDto | undefined;
    image?: MediaFieldDto | undefined;
    tags?: TaxonomyFieldDto | undefined;
    category?: TaxonomyFieldDto | undefined;
}

export class BlogPostItemDto extends ContentItemDto implements IBlogPostItemDto {
    blogPost?: BlogPostDto | undefined;
    titlePart?: TitlePartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    markdownBodyPart?: MarkdownBodyPartDto | undefined;

    constructor(data?: IBlogPostItemDto) {
        super(data);
        this._discriminator = "BlogPostItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.blogPost = _data["blogPost"] ? BlogPostDto.fromJS(_data["blogPost"]) : <any>undefined;
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
            this.autoroutePart = _data["autoroutePart"] ? AutoroutePartDto.fromJS(_data["autoroutePart"]) : <any>undefined;
            this.markdownBodyPart = _data["markdownBodyPart"] ? MarkdownBodyPartDto.fromJS(_data["markdownBodyPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BlogPostItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new BlogPostItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["blogPost"] = this.blogPost ? this.blogPost.toJSON() : <any>undefined;
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        data["autoroutePart"] = this.autoroutePart ? this.autoroutePart.toJSON() : <any>undefined;
        data["markdownBodyPart"] = this.markdownBodyPart ? this.markdownBodyPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IBlogPostItemDto extends IContentItemDto {
    blogPost?: BlogPostDto | undefined;
    titlePart?: TitlePartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    markdownBodyPart?: MarkdownBodyPartDto | undefined;
}

export class BlogDto extends ContentPartDto implements IBlogDto {
    image?: MediaFieldDto | undefined;

    constructor(data?: IBlogDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.image = _data["image"] ? MediaFieldDto.fromJS(_data["image"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BlogDto {
        data = typeof data === 'object' ? data : {};
        let result = new BlogDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["image"] = this.image ? this.image.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IBlogDto extends IContentPartDto {
    image?: MediaFieldDto | undefined;
}

export class BlogItemDto extends ContentItemDto implements IBlogItemDto {
    blog?: BlogDto | undefined;
    titlePart?: TitlePartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    htmlBodyPart?: HtmlBodyPartDto | undefined;
    listPart?: ListPartDto | undefined;

    constructor(data?: IBlogItemDto) {
        super(data);
        this._discriminator = "BlogItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.blog = _data["blog"] ? BlogDto.fromJS(_data["blog"]) : <any>undefined;
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
            this.autoroutePart = _data["autoroutePart"] ? AutoroutePartDto.fromJS(_data["autoroutePart"]) : <any>undefined;
            this.htmlBodyPart = _data["htmlBodyPart"] ? HtmlBodyPartDto.fromJS(_data["htmlBodyPart"]) : <any>undefined;
            this.listPart = _data["listPart"] ? ListPartDto.fromJS(_data["listPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BlogItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new BlogItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["blog"] = this.blog ? this.blog.toJSON() : <any>undefined;
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        data["autoroutePart"] = this.autoroutePart ? this.autoroutePart.toJSON() : <any>undefined;
        data["htmlBodyPart"] = this.htmlBodyPart ? this.htmlBodyPart.toJSON() : <any>undefined;
        data["listPart"] = this.listPart ? this.listPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IBlogItemDto extends IContentItemDto {
    blog?: BlogDto | undefined;
    titlePart?: TitlePartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    htmlBodyPart?: HtmlBodyPartDto | undefined;
    listPart?: ListPartDto | undefined;
}

export class ContainerDto extends ContentPartDto implements IContainerDto {

    constructor(data?: IContainerDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ContainerDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContainerDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IContainerDto extends IContentPartDto {
}

export class ContainerItemDto extends ContentItemDto implements IContainerItemDto {
    container?: ContainerDto | undefined;
    flowPart?: FlowPartDto | undefined;

    constructor(data?: IContainerItemDto) {
        super(data);
        this._discriminator = "ContainerItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.container = _data["container"] ? ContainerDto.fromJS(_data["container"]) : <any>undefined;
            this.flowPart = _data["flowPart"] ? FlowPartDto.fromJS(_data["flowPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ContainerItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContainerItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["container"] = this.container ? this.container.toJSON() : <any>undefined;
        data["flowPart"] = this.flowPart ? this.flowPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IContainerItemDto extends IContentItemDto {
    container?: ContainerDto | undefined;
    flowPart?: FlowPartDto | undefined;
}

export class BlockquoteDto extends ContentPartDto implements IBlockquoteDto {
    quote?: TextFieldDto | undefined;

    constructor(data?: IBlockquoteDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.quote = _data["quote"] ? TextFieldDto.fromJS(_data["quote"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BlockquoteDto {
        data = typeof data === 'object' ? data : {};
        let result = new BlockquoteDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["quote"] = this.quote ? this.quote.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IBlockquoteDto extends IContentPartDto {
    quote?: TextFieldDto | undefined;
}

export class BlockquoteItemDto extends ContentItemDto implements IBlockquoteItemDto {
    blockquote?: BlockquoteDto | undefined;

    constructor(data?: IBlockquoteItemDto) {
        super(data);
        this._discriminator = "BlockquoteItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.blockquote = _data["blockquote"] ? BlockquoteDto.fromJS(_data["blockquote"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BlockquoteItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new BlockquoteItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["blockquote"] = this.blockquote ? this.blockquote.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IBlockquoteItemDto extends IContentItemDto {
    blockquote?: BlockquoteDto | undefined;
}

export class ImageWidgetItemDto extends ContentItemDto implements IImageWidgetItemDto {

    constructor(data?: IImageWidgetItemDto) {
        super(data);
        this._discriminator = "ImageWidgetItemDto";
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): ImageWidgetItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new ImageWidgetItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IImageWidgetItemDto extends IContentItemDto {
}

export class LiquidWidgetItemDto extends ContentItemDto implements ILiquidWidgetItemDto {
    liquidPart?: LiquidPartDto | undefined;

    constructor(data?: ILiquidWidgetItemDto) {
        super(data);
        this._discriminator = "LiquidWidgetItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.liquidPart = _data["liquidPart"] ? LiquidPartDto.fromJS(_data["liquidPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): LiquidWidgetItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new LiquidWidgetItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["liquidPart"] = this.liquidPart ? this.liquidPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface ILiquidWidgetItemDto extends IContentItemDto {
    liquidPart?: LiquidPartDto | undefined;
}

export class ImageDto extends ContentPartDto implements IImageDto {
    media?: MediaFieldDto | undefined;
    caption?: TextFieldDto | undefined;

    constructor(data?: IImageDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.media = _data["media"] ? MediaFieldDto.fromJS(_data["media"]) : <any>undefined;
            this.caption = _data["caption"] ? TextFieldDto.fromJS(_data["caption"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ImageDto {
        data = typeof data === 'object' ? data : {};
        let result = new ImageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["media"] = this.media ? this.media.toJSON() : <any>undefined;
        data["caption"] = this.caption ? this.caption.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IImageDto extends IContentPartDto {
    media?: MediaFieldDto | undefined;
    caption?: TextFieldDto | undefined;
}

export class ImageItemDto extends ContentItemDto implements IImageItemDto {
    image?: ImageDto | undefined;
    titlePart?: TitlePartDto | undefined;

    constructor(data?: IImageItemDto) {
        super(data);
        this._discriminator = "ImageItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.image = _data["image"] ? ImageDto.fromJS(_data["image"]) : <any>undefined;
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ImageItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new ImageItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["image"] = this.image ? this.image.toJSON() : <any>undefined;
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IImageItemDto extends IContentItemDto {
    image?: ImageDto | undefined;
    titlePart?: TitlePartDto | undefined;
}

export class ParagraphDto extends ContentPartDto implements IParagraphDto {
    content?: HtmlFieldDto | undefined;

    constructor(data?: IParagraphDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.content = _data["content"] ? HtmlFieldDto.fromJS(_data["content"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ParagraphDto {
        data = typeof data === 'object' ? data : {};
        let result = new ParagraphDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["content"] = this.content ? this.content.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IParagraphDto extends IContentPartDto {
    content?: HtmlFieldDto | undefined;
}

export class ParagraphItemDto extends ContentItemDto implements IParagraphItemDto {
    paragraph?: ParagraphDto | undefined;

    constructor(data?: IParagraphItemDto) {
        super(data);
        this._discriminator = "ParagraphItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.paragraph = _data["paragraph"] ? ParagraphDto.fromJS(_data["paragraph"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ParagraphItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new ParagraphItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["paragraph"] = this.paragraph ? this.paragraph.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IParagraphItemDto extends IContentItemDto {
    paragraph?: ParagraphDto | undefined;
}

export class RawHtmlDto extends ContentPartDto implements IRawHtmlDto {
    content?: HtmlFieldDto | undefined;

    constructor(data?: IRawHtmlDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.content = _data["content"] ? HtmlFieldDto.fromJS(_data["content"]) : <any>undefined;
        }
    }

    static fromJS(data: any): RawHtmlDto {
        data = typeof data === 'object' ? data : {};
        let result = new RawHtmlDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["content"] = this.content ? this.content.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IRawHtmlDto extends IContentPartDto {
    content?: HtmlFieldDto | undefined;
}

export class RawHtmlItemDto extends ContentItemDto implements IRawHtmlItemDto {
    rawHtml?: RawHtmlDto | undefined;

    constructor(data?: IRawHtmlItemDto) {
        super(data);
        this._discriminator = "RawHtmlItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.rawHtml = _data["rawHtml"] ? RawHtmlDto.fromJS(_data["rawHtml"]) : <any>undefined;
        }
    }

    static fromJS(data: any): RawHtmlItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new RawHtmlItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["rawHtml"] = this.rawHtml ? this.rawHtml.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IRawHtmlItemDto extends IContentItemDto {
    rawHtml?: RawHtmlDto | undefined;
}

export class PageDto extends ContentPartDto implements IPageDto {

    constructor(data?: IPageDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): PageDto {
        data = typeof data === 'object' ? data : {};
        let result = new PageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface IPageDto extends IContentPartDto {
}

export class PageItemDto extends ContentItemDto implements IPageItemDto {
    page?: PageDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    flowPart?: FlowPartDto | undefined;
    titlePart?: TitlePartDto | undefined;

    constructor(data?: IPageItemDto) {
        super(data);
        this._discriminator = "PageItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.page = _data["page"] ? PageDto.fromJS(_data["page"]) : <any>undefined;
            this.autoroutePart = _data["autoroutePart"] ? AutoroutePartDto.fromJS(_data["autoroutePart"]) : <any>undefined;
            this.flowPart = _data["flowPart"] ? FlowPartDto.fromJS(_data["flowPart"]) : <any>undefined;
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): PageItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new PageItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["page"] = this.page ? this.page.toJSON() : <any>undefined;
        data["autoroutePart"] = this.autoroutePart ? this.autoroutePart.toJSON() : <any>undefined;
        data["flowPart"] = this.flowPart ? this.flowPart.toJSON() : <any>undefined;
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IPageItemDto extends IContentItemDto {
    page?: PageDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
    flowPart?: FlowPartDto | undefined;
    titlePart?: TitlePartDto | undefined;
}

export class TagDto extends ContentPartDto implements ITagDto {

    constructor(data?: ITagDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
    }

    static fromJS(data: any): TagDto {
        data = typeof data === 'object' ? data : {};
        let result = new TagDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data; 
    }
}

export interface ITagDto extends IContentPartDto {
}

export class TagItemDto extends ContentItemDto implements ITagItemDto {
    tag?: TagDto | undefined;
    titlePart?: TitlePartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;

    constructor(data?: ITagItemDto) {
        super(data);
        this._discriminator = "TagItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.tag = _data["tag"] ? TagDto.fromJS(_data["tag"]) : <any>undefined;
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
            this.autoroutePart = _data["autoroutePart"] ? AutoroutePartDto.fromJS(_data["autoroutePart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): TagItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new TagItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["tag"] = this.tag ? this.tag.toJSON() : <any>undefined;
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        data["autoroutePart"] = this.autoroutePart ? this.autoroutePart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface ITagItemDto extends IContentItemDto {
    tag?: TagDto | undefined;
    titlePart?: TitlePartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
}

export class CategoryDto extends ContentPartDto implements ICategoryDto {
    icon?: TextFieldDto | undefined;

    constructor(data?: ICategoryDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.icon = _data["icon"] ? TextFieldDto.fromJS(_data["icon"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CategoryDto {
        data = typeof data === 'object' ? data : {};
        let result = new CategoryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["icon"] = this.icon ? this.icon.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface ICategoryDto extends IContentPartDto {
    icon?: TextFieldDto | undefined;
}

export class CategoryItemDto extends ContentItemDto implements ICategoryItemDto {
    category?: CategoryDto | undefined;
    titlePart?: TitlePartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;

    constructor(data?: ICategoryItemDto) {
        super(data);
        this._discriminator = "CategoryItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.category = _data["category"] ? CategoryDto.fromJS(_data["category"]) : <any>undefined;
            this.titlePart = _data["titlePart"] ? TitlePartDto.fromJS(_data["titlePart"]) : <any>undefined;
            this.autoroutePart = _data["autoroutePart"] ? AutoroutePartDto.fromJS(_data["autoroutePart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CategoryItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new CategoryItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["category"] = this.category ? this.category.toJSON() : <any>undefined;
        data["titlePart"] = this.titlePart ? this.titlePart.toJSON() : <any>undefined;
        data["autoroutePart"] = this.autoroutePart ? this.autoroutePart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface ICategoryItemDto extends IContentItemDto {
    category?: CategoryDto | undefined;
    titlePart?: TitlePartDto | undefined;
    autoroutePart?: AutoroutePartDto | undefined;
}

export class BarItemDto extends ContentItemDto implements IBarItemDto {
    htmlBodyPart?: HtmlBodyPartDto | undefined;

    constructor(data?: IBarItemDto) {
        super(data);
        this._discriminator = "BarItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.htmlBodyPart = _data["htmlBodyPart"] ? HtmlBodyPartDto.fromJS(_data["htmlBodyPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BarItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new BarItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["htmlBodyPart"] = this.htmlBodyPart ? this.htmlBodyPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IBarItemDto extends IContentItemDto {
    htmlBodyPart?: HtmlBodyPartDto | undefined;
}

export class FooItemDto extends ContentItemDto implements IFooItemDto {
    markdownBodyPart?: MarkdownBodyPartDto | undefined;

    constructor(data?: IFooItemDto) {
        super(data);
        this._discriminator = "FooItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.markdownBodyPart = _data["markdownBodyPart"] ? MarkdownBodyPartDto.fromJS(_data["markdownBodyPart"]) : <any>undefined;
        }
    }

    static fromJS(data: any): FooItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new FooItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["markdownBodyPart"] = this.markdownBodyPart ? this.markdownBodyPart.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IFooItemDto extends IContentItemDto {
    markdownBodyPart?: MarkdownBodyPartDto | undefined;
}

export class BagItemDto extends ContentItemDto implements IBagItemDto {
    items?: BagPartDto | undefined;

    constructor(data?: IBagItemDto) {
        super(data);
        this._discriminator = "BagItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.items = _data["items"] ? BagPartDto.fromJS(_data["items"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BagItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new BagItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["items"] = this.items ? this.items.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IBagItemDto extends IContentItemDto {
    items?: BagPartDto | undefined;
}

export class FooTextDto extends ContentPartDto implements IFooTextDto {
    fooField?: TextFieldDto | undefined;

    constructor(data?: IFooTextDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.fooField = _data["fooField"] ? TextFieldDto.fromJS(_data["fooField"]) : <any>undefined;
        }
    }

    static fromJS(data: any): FooTextDto {
        data = typeof data === 'object' ? data : {};
        let result = new FooTextDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fooField"] = this.fooField ? this.fooField.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IFooTextDto extends IContentPartDto {
    fooField?: TextFieldDto | undefined;
}

export class FooTextItemDto extends ContentItemDto implements IFooTextItemDto {
    fooText?: FooTextDto | undefined;

    constructor(data?: IFooTextItemDto) {
        super(data);
        this._discriminator = "FooTextItemDto";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.fooText = _data["fooText"] ? FooTextDto.fromJS(_data["fooText"]) : <any>undefined;
        }
    }

    static fromJS(data: any): FooTextItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new FooTextItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fooText"] = this.fooText ? this.fooText.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IFooTextItemDto extends IContentItemDto {
    fooText?: FooTextDto | undefined;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}